services:
  mysql:
    image: mysql:8.4
    container_name: prestamos-mysql
    restart: always
    environment:
      MYSQL_DATABASE: dev_prestamos
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3311:3306"
    networks:
      - prestamos-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      interval: 10s

  eurekaserver:
    build:
      context: ../eurekaserver
    image: eurekaserver:1.0
    container_name: prestamos-eurekaserver
    ports:
      - "8761:8761"
    networks:
      - prestamos-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 10s

  prestamos:
    build:
      context: .
    image: prestamos:1.0
    container_name: prestamos-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8085:8085"
    networks:
      - prestamos-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      timeout: 10s
      retries: 5
      interval: 10s

networks:
  prestamos-network:
    driver: bridge
