spring.application.name=dev.auditoria
spring.datasource.url=jdbc:mysql://localhost:3306/auditoria_db
spring.datasource.username=auditoria
spring.datasource.password=auditoria123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
springdoc.swagger-ui.path=/swagger-ui.html

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

logging.level.dev.diemigo.dev.auditoria=DEBUG
logging.level.org.hibernate.SQL=warn

